# Generated by Django 5.2.7 on 2025-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
